# Generated by Django 4.2.2 on 2023-06-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('report_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_on', models.BooleanField(default=True)),
                ('task_status', models.CharField(blank=True, default='Success', max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('scheduler_type', models.CharField(blank=True, max_length=100, null=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
