# Generated by Django 4.2.2 on 2023-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMSapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launchscheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('logs', models.CharField(default='logdata', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('scheduler_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
