# Generated by Django 4.2.2 on 2023-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NMSapplication', '0002_launchscheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchscheduler',
            name='logs',
            field=models.TextField(),
        ),
    ]
